### ISSUE TITLE
File actions don't work

### ISSUE THREAD

**Issue by ntinti** [nrlquaker/winbox-mac#33] opened 2020-01-24 23:32 UTC
File open or safe and Tools import / export doesn't work . Wnbox-mac freezes and has to be killed

 - macOS version:catalina
 - macOS language German
 - Winbox-mac version: 3.20.4

**Comment by nrlquaker** [comment] 2020-01-24 23:33
Its a know issue and will be fixed in the next version.

**Closed by nrlquaker** 2020-01-24 23:33 UTC

**Comment by nrlquaker** [comment] 2020-01-24 23:44
You can try [v3.20.5-rc1](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.20.5-rc1). The issue is fixed there.

**Comment by ntinti** [comment] 2020-01-24 23:56
It works - THANKS a lot !

**Comment by nrlquaker** [comment] 2020-01-24 23:58
Please report if you'll find any issues in this version.

**Comment by mattgorecki** [comment] 2020-01-31 00:22
Using v3.20.5-rc1 fixes the freeze when trying to open the upload file dialog box. However, it doesn't show the contents of the Downloads, Documents or Desktop folders.  If I create a new folder in my home directory (/Users/username/), the contents of that folder will be visible.
