### ISSUE TITLE
Can't resize Winbox Windows

### ISSUE THREAD

**Issue by mmorier86** [nrlquaker/winbox-mac#42] opened 2020-03-05 15:00 UTC
**Checklist**

- [ X ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [ X ] I made sure this is not the original Winbox issue.

**Describe the bug**
Winbox open, but can't resize the windows and after I connect to a ROS Router, the app crash.
Got only the problem on a new macOS 10.15.3 ( but all the user profile was restored from an old Mac not running Catalina and where wine ( older version ) and XQuartz ( old version ) was use. So maybe event if the package have up to date wine64 a Library from old installation is loaded.

**To Reproduce**
Just open Winbox-mac and try to resize the window, it does not work.

**Expected behavior**
Windows can be resize on an other macOS running Catalina ( fresh install )

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version: 10.15.3
 - macOS language French
 - Winbox-mac version 3.21
 - Winbox version 3.21

**Additional context**
The installation where the problem occur is a macOS Catalina where a Time Machine from 10.12 where imported, so the user Library may be different from a 10.15 user Library.

**Comment by mmorier86** [comment] 2020-03-05 15:06
Tried with a new profile on Catalina and Winbox-mac work correctly.

What file on my old profile ( /Users/%username% ) could be wrong ?

**Comment by nrlquaker** [comment] 2020-03-05 15:09
Try to remove ~/.wine.

**Comment by mmorier86** [comment] 2020-03-05 15:14
Already tried this ~/.wine
and all trace of wine or Winbox I could find in ~/Library/

**Comment by nrlquaker** [comment] 2020-03-05 15:15
Please provide log running:
`/Applications/Winbox-mac.app/Contents/MacOS/winbox-mac`

**Comment by mmorier86** [comment] 2020-03-05 15:21
Here is an exemple connecting to and old dev board 

------------------------------------------

matmor@mac-matmor ~ % /Applications/Winbox-mac.app/Contents/MacOS/winbox-mac
creating Window Class routeros_null
creating Window Class routeros_connect
DPI=96
EMS=13
ERROR: bad bmp format id=2329
biPlanes=1, biBitCount=1, biCompression=0
ERROR: bad bmp format id=3329
biPlanes=1, biBitCount=1, biCompression=0
creating Window Class routeros_dbl_canvas
 discovery started
rescaning
002b:fixme:winsock:set_dont_fragment IP_DONTFRAGMENT for IPv4 not supported in this platform
connecting to 127.255.255.255
connecting to 192.168.131.255
connecting to 169.254.255.255
connecting to 169.254.255.255
002b:fixme:winsock:set_dont_fragment IP_DONTFRAGMENT for IPv6 not supported in this platform
002b:fixme:winsock:WS_setsockopt Unknown IPPROTO_IPV6 optname 0x0000000c
IPV6_ADD_MEMBERSHIP: 0
loadConfig C:\users\matmor\Application Data\Mikrotik\Winbox\Addresses.cdb
ConnectWindow::onConnect
discovery stopped
startKeyExchange
sending first challenge
kex failed
sending first handshake
doing handshake
~Discovery
discovery stopped
loading C:\users\matmor\Application Data\Mikrotik\Winbox\6.38rc49-1097823211\roteros.jg
loading C:\users\matmor\Application Data\Mikrotik\Winbox\6.38rc49-1097823211\advtool.jg
loading C:\users\matmor\Application Data\Mikrotik\Winbox\6.38rc49-1097823211\dhcp.jg
loading C:\users\matmor\Application Data\Mikrotik\Winbox\6.38rc49-1097823211\hotspot.jg
loading C:\users\matmor\Application Data\Mikrotik\Winbox\6.38rc49-1097823211\mpls.jg
loading C:\users\matmor\Application Data\Mikrotik\Winbox\6.38rc49-1097823211\ppp.jg
loading C:\users\matmor\Application Data\Mikrotik\Winbox\6.38rc49-1097823211\roting4.jg
loading C:\users\matmor\Application Data\Mikrotik\Winbox\6.38rc49-1097823211\secure.jg
loading C:\users\matmor\Application Data\Mikrotik\Winbox\6.38rc49-1097823211\wlan6.jg
ConnectWindow::destroyed
App::saveAllSettings
App::saveAllSettings done
saving settings to .\viwf589.tmp... for C:\users\matmor\Application Data\Mikrotik\Winbox\settings.cfg.viw
settings saved
~ConnectWindow
~ConnectWindow done
run
boardName=<RB433>
boardArch=<mips>
boardFamily=<RB400>
logged in!!!
creating Window Class routeros_main
creating Window Class routeros_pane
creating Window Class routeros_canvas
MainWindow::start
got qs caps=79
loading all settings
WindowManager::init end
startServices
startServices done
App::saveAllSettings
MainWindow::saveSettings
App::saveAllSettings done
saving settings to .\viw3ea4.tmp... for C:\users\matmor\Application Data\Mikrotik\Winbox\sessions\192.168.129.98.viw
settings saved
closing down
MainWindow::destroyed
~MainWindow
~MainWindow done
~Connection
exiting
WARNING: deleting font h=0xce0056
WARNING: deleting font h=0x100160
------------------------------------------

The app did not crash, but since it's impossible de resize the windows and the Winbox main window open at only a couple pixel width ... it's impossible to use

Hope you have an idea of what file could be the problem

**Comment by nrlquaker** [comment] 2020-03-05 15:43
> Winbox main window open at only a couple pixel width

Can you provide a screenshot?
Never seen such behaviour.

**Comment by mmorier86** [comment] 2020-03-05 15:50
https://pasteboard.co/IXHKwpa.png
https://pasteboard.co/IXHKFVE.png

And if I try to resize .. the max I can get is

https://pasteboard.co/IXHKOJc.png

**Comment by mmorier86** [comment] 2020-03-05 15:51
Winbox-Mac seem to work fine ... but don't know why can't resize the windows ... so not really useful 
https://pasteboard.co/IXHLbHH.png

**Comment by nrlquaker** [comment] 2020-03-05 15:52
Please provide exact `Winbox-mac` version. Its 3.21.0 or 3.21.1.

**Comment by mmorier86** [comment] 2020-03-05 15:54
The latest ( 3.21.1 ) , I tried reinstall before opening an issue ( brew cask reinstall nrlquaker-winbox )

**Comment by nrlquaker** [comment] 2020-03-05 15:55
Will look what I can do here.

**Comment by nrlquaker** [comment] 2020-03-12 10:36
It seems its related to xQuartz. I couldn't reproduce the issue, but my friend got it on one of his machines. Can you try installing `xQuartz` and `freetype`? If it will not help remove `libpng*.dylib`, `libfreetype.6.dylib` and `libfontconfig.1.dylib` from `Winbox-mac.app/Contents/Resources/wine/lib64`.

**Comment by mmorier86** [comment] 2020-03-12 13:09
Thanks for your reply, I already have XQuartz 2.7.11 ( xorg-server 1.18.4 ) installed
freetype 2.9.1 was already install, I upgraded to 2.10.1 and still have the same problem

Also removed the files you have tell me, still have the same problem ( on my curent session, not ona new session on the same Mac )

matmor@mac-matmor ~ % cd /Applications/Winbox-mac.app/Contents/Resources/wine/lib64 
matmor@mac-matmor lib64 % ls
libfontconfig.1.dylib	libpng15.15.dylib	libwine.1.0.dylib	libwine.dylib
libfreetype.6.dylib	libpng16.16.dylib	libwine.1.dylib		wine
matmor@mac-matmor lib64 % rm -rf libpng*.dylib
matmor@mac-matmor lib64 % rm -rf libfreetype.6.dylib 
matmor@mac-matmor lib64 % rm -rf libfontconfig.1.dylib

**Comment by nrlquaker** [comment] 2020-03-12 13:27
Very strange.
To sort it out:
- problem only occurs when you restore user folder from Timemachine;
- on fresh Catalina there is no problem.
Is it correct?

Why do you have xQuartz on fresh install?

**Comment by mmorier86** [comment] 2020-03-12 13:58
Had xQuartz probably from my Time Machine when I switched on this new MacMini causse I was using it with wine on my old Mac mini to run Winbox 32bit

**Comment by mmorier86** [comment] 2020-03-12 13:58
But yes, on fresh Catalina your bundle work correctly without any other app needed. 
And on the same Mac mini it work OK on a new profile

**Comment by nrlquaker** [comment] 2020-03-12 14:28
Well, its seems that something in the `~/` causes the problem. You can try to search for `wine` and `xQuartz` leftovers and remove them and/or run:
```
brew cask zap zquartz --force
brew cask zap wine-{stable,devel,staging} --force
```

**Comment by nrlquaker** [comment] 2020-03-12 14:29
But don't forget to reinstall `winbox-mac` to recover deleted `dylibs`.

**Comment by nrlquaker** [comment] 2020-03-13 10:01
Can you try to add
`export DYLD_FALLBACK_LIBRARY_PATH="$(dirname "$0")/../Resources/wine/lib64"`
to `Winbox-mac.app/Contents/MacOS/winbox-mac` at the end of exports? And see if it helps.

**Comment by mmorier86** [comment] 2020-03-17 12:14
Just add the problem on my new Mac Book pro where your winbox was working correctly.
So now I don't think it's due to a Time Machine Backup ... but more to DUET DISPLAY

Since I work from home, I have install DUET to use my iPad as a second screen and since them I can't resize the winbox windows when I open it !

Any idea what could be the problem ? Or should I open a ticket with DUET ?

**Comment by engur** [comment] 2020-03-26 00:52
19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

and the problem also occurs when i use sidecar with an ipad (using as a separate display)

**Comment by mmorier86** [comment] 2020-03-26 12:59
Contacted Duet and according to them it look like it's more on the WINE side that the problem is with external faked display like DUET and SIDECAR.

Duet had many report of problem with wine app on Catalina

**Comment by nrlquaker** [comment] 2020-04-05 13:00
According to comments the problem is not in `Winbox-mac`, but in Wine. Closing.

**Closed by nrlquaker** 2020-04-05 13:00 UTC

**Comment by flotpg** [comment] 2020-08-03 08:46
Bugzilla issue of WineHQ project: https://bugs.winehq.org/show_bug.cgi?id=48896

**Comment by nrlquaker** [comment] 2020-08-03 09:04
@flotpg thanks for the link.

**Comment by flotpg** [comment] 2020-08-03 09:12
@nrlquaker thx for your work ;)
I just stumbled upon your project, nice!
