### ISSUE TITLE
Window resize issue

### ISSUE THREAD

**Issue by Talhazzers** [nrlquaker/winbox-mac#109] opened 2022-10-17 22:29 UTC
**Checklist**

- [+] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [+] I made sure this is not the original Winbox issue.

**Describe the bug**
WinBox's window size does not persist when edited. When I restart WinBox it starts in the old window position.

**Desktop (please complete the following information):**
 - macOS version: 12.6
 - macOS language Turkish
 - Winbox-mac version 3.37 (latest)
 - Winbox version 3.37 (latest)

**Comment by rstaph** [comment] 2022-10-25 03:38
Same issue, but additionally on resize the usable area is vertically limited, even when the Mac window boundaries are resized. 

macOS version: 12.3.1
macOS language: English
Winbox-mac version 3.37

If I edit Winbox-mac.app/Contents/Resources/wine/share/wine/wine.inf to contain a reference to: HKLM,Software\Explorer\Desktops,"1920x1080"
It will allow resizing and remember the size for a random number of runs of the app, most of the time it still forgets immediately.

**Comment by mthoodlum** [comment] 2022-11-01 02:55
Same issue. I connect to Winbox, maximize the window, then click "New Winbox" to open a new Winbox window. I can resize the new Winbox window. I then close the original Winbox session.

**Comment by Potewol** [comment] 2022-11-04 17:42
I have the same issue after upgrading to ventura. All was well before the upgrade and also worked with the beta ventura releases

**Comment by mthoodlum** [comment] 2022-11-04 18:06
Yes @Potewol, I also recently upgraded to Ventura and now winbox-mac is unusable. I installed Wine and run winbox64.exe directly, which works, but no copy/paste shortcut keys, which is a bummer.

@nrlquaker the change log says to contact you if interested in being a maintainer. I am interested but there is no contact info. I'd love to help maintain this project.

**Comment by nrlquaker** [comment] 2022-11-04 19:52
@mthoodlum my email is on every commit. Please use it.

**Comment by turnkeyisp-david** [comment] 2022-11-04 23:50
@nrlquaker, this is what a commit looks like from my perspective. I don't see an email address there.

<img width="1268" alt="Screenshot 2022-11-04 at 6 48 35 PM" src="https://user-images.githubusercontent.com/96998293/200090399-89eddc9e-c14c-4c78-a094-99a813a12f0e.png">

**Comment by nrlquaker** [comment] 2022-11-04 23:53
@turnkeyisp-david I'm sorry, If you don't know how to view email in git you shouldn't be a maintainer.

**Comment by nrlquaker** [comment] 2022-11-04 23:57
@mthoodlum @turnkeyisp-david please don't use this issue to discuss issue not related to this one.

**Comment by nrlquaker** [comment] 2022-11-05 00:14
Seems like a `wine` issue. Please report it on [their forum](https://bugs.winehq.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=NEEDINFO&bug_status=STAGED&product=Wine&columnlist=bug_severity,priority,bug_status,cf_regression_sha1sum,short_desc,changeddate&keywords=regression&keywords_type=anywords).

**Comment by mthoodlum** [comment] 2022-11-19 23:02
I have Wine installed on my Macbook Air M1 with Ventura and when I open winbox64.exe using Wine then I don't have this window resize problem. I do experience this problem every time with winbox-mac which makes winbox-mac unusable. Now I just use Wine and lose keyboard shortcuts for copy/paste but at least Winbox is usable.

**Comment by dario-pilori** [comment] 2022-12-10 16:55
I'm having the same issue on an English-language version of MacOS 13.0.1 (ventura) on the M1 Pro platform.

> Seems like a `wine` issue. Please report it on [their forum](https://bugs.winehq.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=NEEDINFO&bug_status=STAGED&product=Wine&columnlist=bug_severity,priority,bug_status,cf_regression_sha1sum,short_desc,changeddate&keywords=regression&keywords_type=anywords).

I also thought that this could have been a wine-related issue, but if I change the slash-bang of the application to `#!/bin/bash` and I run it from a Terminal (e.g. by running `/Applications/Winbox-mac.app/Contents/MacOS/winbox-mac`) everything works perfectly.

Therefore, I suspect that the issue is not on wine, but instead in the way wine is called. I tried several times, but I couldn't find a way to find what is causing the issue.

**Comment by nrlquaker** [comment] 2022-12-13 10:39
@dario-pilori thanks for the info. But does it works after changing shebang when app launches normally?

**Comment by Talhazzers** [comment] 2022-12-14 10:21
I couldn't see a problem when starting winbox-mac using terminal.

**Comment by dario-pilori** [comment] 2022-12-20 08:45
> @dario-pilori thanks for the info. But does it works after changing shebang when app launches normally?

No, it does not work. 

Actually, I tested it also without changing the shebang, and it works. So, it seems that the only difference is running it using Terminal.

**Comment by panzer-arc** [comment] 2023-01-21 20:54
Good find @dario-pilori. Running from zsh/iTerm also worked for me. I don't think bash is necessary.

**Comment by nrlquaker** [comment] 2023-01-21 20:57
@Gcenx sorry for a ping, but do you have any ideas about he issue?

**Comment by kristofferR** [comment] 2023-01-21 21:23
`sudo codesign -s - --deep --force /Applications/Winbox.app` may solve the issue. 

I figured that running it from Terminal could perhaps handle signatures differently. I noticed that the app was completely unsigned before. After I ran codesign I haven't experienced any window resizing issues.

**Comment by dario-pilori** [comment] 2023-01-21 22:09
> Try signing it using the command and report back.

I tried with the command you suggested. It worked only a couple of times, than it stopped working again.

**Comment by nrlquaker** [comment] 2023-01-21 22:14
@kristofferR to sign it you need a developer account. Unfortunately I don't have. it.

**Comment by Gcenx** [comment] 2023-01-24 19:11
> @Gcenx sorry for a ping, but do you have any ideas about the issue?

No clue, maybe it will improve after bumping to wine-8.0

**Comment by nrlquaker** [comment] 2023-03-21 08:37
Maybe #117 will fix it.

**Comment by kubert96** [comment] 2023-03-21 08:41
One question. That i dont se in this. Is this specific to M1 or M2 mac? 
I personaly run M1 Pro 

<img width="214" alt="Screenshot 2023-03-21 at 09 41 49" src="https://user-images.githubusercontent.com/68554211/226555183-14f3862f-3e1a-4dcf-82a1-a100f74e4e2a.png">

**Comment by nrlquaker** [comment] 2023-03-21 08:48
@kubert96 hard to say. On M1 it sometimes happens for me.

**Comment by florian-obradovic** [comment] 2023-03-22 16:23
I have the same issue (even on the new v3.37.1). I can't resize the window until I connect > disconnect or create a new window. The cursor is locked / trapped inside the window.
All on current macOS (M2 or M1Max)
![CleanShot 2023-03-22 at 17 21 34](https://user-images.githubusercontent.com/57985125/226971358-8a323faf-0e82-4dc8-bd1a-c5d7af901083.gif)

**Comment by nrlquaker** [comment] 2023-03-22 16:27
Guys with the issue, please download [full wine](https://github.com/Gcenx/macOS_Wine_builds/releases/download/8.0/wine-stable-8.0-osx64.tar.xz) and replace content of `/Applications/Winbox-mac.app/Contents/Resources/wine` with downloaded wine. And test. Thanks.

**Comment by kubert96** [comment] 2023-03-22 17:15
Run one more time. But i open winbox64.exe (Located in winbox-mac app) with wine and it works OK. 

<img width="431" alt="Screenshot 2023-03-22 at 18 13 35" src="https://user-images.githubusercontent.com/68554211/226984703-b6b490d8-f223-4a33-9bd6-984caae38222.png">

When i run winbox-mac than it is broken as @florian-obradovic show in video.

**Comment by Gcenx** [comment] 2023-03-22 17:18
This sounds like the winbox-Mac prefix is causing the issues as wine-stable-8.0 from brew and the build found in #118 is the exact same just stripped the useless i386 stuff.

**Comment by kubert96** [comment] 2023-03-22 17:25
https://user-images.githubusercontent.com/68554211/226987681-3443ad0a-99aa-44df-b9a3-26c54628ac55.mp4

**Comment by kubert96** [comment] 2023-03-22 17:34
I just reinstall the package... 
On first run everithing was OK. Running as it should. Resizing and moving window worked as expected. 

But when i close and open app again it start to do exxactly what it is doing in previsions coment. 

<img width="1127" alt="Screenshot 2023-03-22 at 18 33 03" src="https://user-images.githubusercontent.com/68554211/226989630-cf00d78f-e690-46a4-9d80-59c5234a8255.png">

**Comment by Gcenx** [comment] 2023-03-22 17:39
> I just reinstall the package... On first run everithing was OK. Running as it should. Resizing and moving window worked as expected.
> 
> But when i close and open app again it start to do exxactly what it is doing in previsions coment.
> 
> <img alt="Screenshot 2023-03-22 at 18 33 03" width="1127" src="https://user-images.githubusercontent.com/68554211/226989630-cf00d78f-e690-46a4-9d80-59c5234a8255.png">

The package abalone from brew is still using wine-7.0

**Comment by kubert96** [comment] 2023-03-22 17:48
With new release i tested clean install and it doesnt scale or move window properly right away. 

Tested with clean install of [v3.37.1]
And another test with clean install [v3.37.1] and wine content repleaced from oficial Wine Release.

**Comment by Gcenx** [comment] 2023-03-22 17:54
But your not really doing a clean install unless you’ve manually removed the wineprefix that’s in `~/Library/Application Support/com.mikrotik.winbox`

**Comment by the-project-group** [comment] 2023-03-22 21:01
Just tried it on my second mac.

1. Removed 3.37.0 from Applications
2. installed 3.37.1
3. first start < cursor is trapped in window, can't resize
4. quit the app and restart > resize is possible
5. restarted multiple times since then and it still works... will keep you posted if things change.

On my other mac (m1max) I also noticed that the colour if the surface (windows forms?) went from old grey to a lighter/brighter white colour... Not so on my M2...

I didn't clean ~/Library/Application Support/com.mikrotik.winbox yet...

**Comment by arsenieciprian** [comment] 2023-03-26 10:08
same issue here

**Comment by arsenieciprian** [comment] 2023-03-26 10:38
> Guys with the issue, please download [full wine](https://github.com/Gcenx/macOS_Wine_builds/releases/download/8.0/wine-stable-8.0-osx64.tar.xz) and replace content of `/Applications/Winbox-mac.app/Contents/Resources/wine` with `Wine Stable.app/Contents/Resources/wine` from the downloaded archive. And test. Thanks.

It works for me

**Comment by turnkeyisp-david** [comment] 2023-03-26 11:58
Thanks @arsenieciprian ! This actually works.

**Comment by Potewol** [comment] 2023-03-27 04:15
@arsenieciprian, I tried that and my winbox is very zoomed in and once logged into the router, I can't move the cursor. Had to do a force stop on the program. Will try again and let you know

**Comment by rstaph** [comment] 2023-03-27 12:24
> @arsenieciprian, I tried that and my winbox is very zoomed in and once logged into the router, I can't move the cursor. Had to do a force stop on the program. Will try again and let you know

Same here.  Everything is scaled super large and it still doesn't save window sizes.  Ventura 13.2

**Comment by florian-obradovic** [comment] 2023-04-01 17:37
@arsenieciprian I tried your suggested method.
Now I get a bigger window, but I'm still trapped:
![CleanShot 2023-04-01 at 19 35 37](https://user-images.githubusercontent.com/57985125/229306058-1b0f533d-4668-46ef-a26f-3b1efc8f242f.gif)

**Comment by kubert96** [comment] 2023-04-19 10:09
OK got it: 

Removed 3.37.0 from Applications
deleted ~/Library/Application Support/com.mikrotik.winbox
installed 3.37.1 from ZIP - DONT open
Download Wine from Brew (brew tap homebrew/cask-versions , brew install --cask --no-quarantine wine-stable)
Repleaced WINE folder from WINE-stable Install to Winbox 3.37.1 package
And started Winbox from aplication folder with right click and Open. (Accept to install some .net somthing)
After first run you can add it to LunchBar... and lunch it from there :) 

Colors of interface are OK, Resazing works as intended, moving window is OK, no traped cursor in winbox window. 

Imported Address OK. 

Closed multiple times. Macbook restart. And it works. Finaly :) 

@nrlquaker @Gcenx

**Comment by rstaph** [comment] 2023-04-19 13:38
Thank you, kubert96, your method worked for me!

**Comment by Potewol** [comment] 2023-04-20 05:46
> OK got it:
> 
> Removed 3.37.0 from Applications deleted ~/Library/Application Support/com.mikrotik.winbox installed 3.37.1 from ZIP - DONT open Download Wine from Brew (brew tap homebrew/cask-versions , brew install --cask --no-quarantine wine-stable) Repleaced WINE folder from WINE-stable Install to Winbox 3.37.1 package And started Winbox from aplication folder with right click and Open. (Accept to install some .net somthing) After first run you can add it to LunchBar... and lunch it from there :)
> 
> Colors of interface are OK, Resazing works as intended, moving window is OK, no traped cursor in winbox window, neighbor discovery works to
> 
> Imported Address OK.
> 
> Closed multiple times. Macbook restart. And it works. Finaly :)
> 
> @nrlquaker @Gcenx
> 
> <img alt="Screenshot 2023-04-19 at 12 10 13" width="222" src="https://user-images.githubusercontent.com/68554211/233043242-adec607a-0bf1-4c19-892b-1c286c0ead7a.png">
> 
> Apple M1 Pro 14 inch 1Tb disk Ventura 13.3.1

Worked perfectly. Thank you

**Comment by nrlquaker** [comment] 2023-04-21 17:28
@kubert96 what `wine-stable` version are you using?

**Comment by kubert96** [comment] 2023-04-21 17:32
@nrlquaker ==> wine-stable: 8.0

 brew info wine-stable
==> wine-stable: 8.0
https://wiki.winehq.org/MacOS
/opt/homebrew/Caskroom/wine-stable/8.0 (125B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/wine-stable.rb
==> Name
WineHQ-stable

**Comment by Gcenx** [comment] 2023-04-21 17:35
wine-8.0 has issues on macOS Ventura especially 13.3 and later, wine-8.0.1 was tagged and latest includes some required cherry picked commits specifically for macOS Ventura 13.3+ along with some partial fixes for experimental WoW64 (still required the out of free patches)

**Comment by kubert96** [comment] 2023-04-21 17:37
@nrlquaker great info :D But mi fix work perfetly (Other 2 users comfirmed). 
Finaly i can use Winbox normaly :) 

So what the problem with actual build?

**Comment by gavalierm** [comment] 2023-05-09 14:20
Issue persits even in the latest release.

The fix described here works..

**Comment by wmbin** [comment] 2023-05-26 15:48
Disable RetinaMode restore in wine.inf

**Comment by gavalierm** [comment] 2023-05-27 20:17
> 

Nothing like that in my wine.inf

**Comment by wmbin** [comment] 2023-05-28 16:14
`HKCU,Software\Wine\Mac Driver,"RetinaMode",2,"Y"`   wine.inf Disable

**Comment by gavalierm** [comment] 2023-05-28 17:41
> `HKCU,Software\Wine\Mac Driver,"RetinaMode",2,"Y"` wine.inf Disable

Can you be more specific? Where.. How.. ..

**Comment by nevrending** [comment] 2023-06-06 05:18
> `HKCU,Software\Wine\Mac Driver,"RetinaMode",2,"Y"` wine.inf Disable

This seems to work for me.

For those wondering how to do this:

1.  Right click on `Winbox-mac > Show Package Contents`. Go to `Contents > Resources > wine > share > wine`
![image](https://github.com/nrlquaker/winbox-mac/assets/4745298/c5098202-ce9d-4ba5-bd1a-67183e3529df)
2. Open `wine.inf`, find `HKCU,Software\Wine\Mac Driver,"RetinaMode",2,"Y"`, around Line 720
3. Add a `;` in front of the line to disable it. e.g `;HKCU,Software\Wine\Mac Driver,"RetinaMode",2,"Y"`
4. Save

**Comment by kubert96** [comment] 2023-06-06 13:24
@nevrending 

OK great this works too, but "Main" interface not scaling as ist should. 
But steel usefull fix :)  

Thet behavior is expected when disabled "RetinaMode" 

You can steel scale down other elements with Comand +- 👍 

<img width="734" alt="Screenshot 2023-06-06 at 15 22 16" src="https://github.com/nrlquaker/winbox-mac/assets/68554211/58bb06c8-e370-46fb-8874-2cb454a1ac99">

**Comment by actck** [comment] 2023-06-19 16:27
M1 max, 12.6.6 Monterey

I found that the problem of window resize can be solved like this: 

1. open winbox-mac
2. let the window lose focus
3. re-focus the winbox
4. window resize the window, the problem disappears

**Comment by dario-pilori** [comment] 2023-07-30 15:22
After upgrading Winbox to v3.39 and replacing wine with the latest development version (v.8.10), the problem seems solved, at least on my Mac (Ventura 13.5, M1 Pro).

**Comment by Potewol** [comment] 2023-08-03 12:58
> After upgrading Winbox to v3.39 and replacing wine with the latest development version (v.8.10), the problem seems solved, at least on my Mac (Ventura 13.5, M1 Pro).

This worked for me as well, 2020 Macbook Air Ventura 13.5

**Comment by nrlquaker** [comment] 2023-08-13 00:17
Should be fixed in the [latest release](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.39.0).

**Closed by nrlquaker** 2023-08-13 00:17 UTC
