### ISSUE TITLE
Suspicious connection from app

### ISSUE THREAD

**Issue by antwal** [nrlquaker/winbox-mac#24] opened 2019-11-18 15:41 UTC
**Checklist**

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.
- [x] I made sure this is not a [known issue](https://github.com/nrlquaker/winbox-mac#known-issues).

**Describe the bug**
the application requires connection to github but for what reason? winbox has never required external connections. if the external connection is not enabled, the app does not work, so for the moment I use the joshaven version

**To Reproduce**
1. Click winbox-mac app

**Expected behavior**
the application should work immediately without external calls

**Screenshots**
![image](https://user-images.githubusercontent.com/410736/69066337-656c0d00-0a21-11ea-9c06-ceb3e102d41b.png)

**Desktop (please complete the following information):**
 - macOS version: 10.12.6
 - macOS language Italian
 - Winbox-mac version 3.20.2
 - Winbox version 3.20

**Comment by nrlquaker** [comment] 2019-11-18 17:35
Thanks for the report.
Winetricks is from WineBottler. And there [the source](https://bitbucket.org/winebottler/winebottler/src/master/Winetricks/) is old and has no mentioning of requests.
Let me see what can I do.
But the way do you have full url of request?

**Comment by nrlquaker** [comment] 2019-11-18 19:11
The issue is fixed in the [latest release](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.20.3). If you want to use `Homebrew` please wait till this [PR](https://github.com/Homebrew/homebrew-cask/pull/72779) is merged.

About the request I think it downloads [winetricks](https://github.com/Winetricks/winetricks/blob/master/src/winetricks). But I can't be sure because sources are not available.

**Closed by nrlquaker** 2019-11-18 19:11 UTC
